spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:192.168.1.4}:${DATASOURCE_PORT:5432}/${DATASOURCE_DB:ms}?useUnicode=true&characterEncoding=UTF-8
    username: ${DATASOURCE_USER:tq}
    password: ${DATASOURCE_PASS:t@q}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
