eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_SERVICE:192.168.1.4:8761}/eureka/
  instance:
    prefer-ip-address: true
#    hostname: localhost
