eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_HOST:ms.tq.com}:${REGISTRY_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
#    hostname: localhost
