spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://192.168.1.4:5432/ms?useUnicode=true&characterEncoding=UTF-8}
    username: ${DATASOURCE_USER:tq}
    password: ${DATASOURCE_PASS:t@q}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
